'-----------------------------------
' UML concepts illustrated
' JMB 2014
'-----------------------------------
@startuml
'-----------------------------------

class PROFS {
        NOM
        PRENOM
        SEVERITE
}

'-----------------------------------
@enduml
'-----------------------------------
